sonar.projectKey=JesusJC15_salud-de-una-backend
sonar.organization=jesusjc15

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts, **/*.test.ts, **/__tests__/**, **/__test__/**, **/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info